// VARIABLES
@host = https://my.zerotier.com/api
@authToken = bearer mPXKrT8RgK7bQgQg4xDvjJLcNrVdOE0M

// GENERAL
GET {{host}}/status HTTP/1.1

###

//{{requestName.response.body.$.token}}
GET {{host}}/randomToken HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}


###

// NETWORKS
GET {{host}}/network HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

###

//
GET {{host}}/network/8056c2e21cfb6fca HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

###

POST {{host}}/network/1c33c1ced0ed6ae5 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "description": "This is my second network.",
    "config": {
        "enableBroadcast": true
    }
}

###

POST {{host}}/network HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "id": "",
     "config": {
        "enableBroadcast": true,
        "name": "steve"
    }
}



