#!/bin/bash
osver=$(defaults read loginwindow SystemVersionStampAsString | sed 's/10.//g' )
intosver=$(printf %.0f $(echo "$osver" | bc -l))
if [[ $intosver -lt 11 ]]; then 
osascript -e 'display dialog "You need Mac OS 10.11 El Capitan or Higher for this application to work, please upgrade your Mac OS." buttons {"Exit"}'
sleep 1
osascript -e 'tell application "NowYouHearMeConnect" to quit'
osascript -e 'tell application "Terminal" to quit' &
exit
fi
if ! ping -q -c 2 -W 1 8.8.8.8 >/dev/null; then osascript -e 'display dialog "You are not connected to the Internet, or at least NowYouHearMe Connect could not ping Google. \n\nCheck your connection or reboot your computer." buttons {"OK"}' & osascript -e 'tell application "NowYouHearMeConnect" to quit' & osascript -e 'tell application "Terminal" to quit' & exit; fi
if [ -f '/Library/Application Support/nowyouhearme/last-session-ztid.txt' ]; then
oldztid=$(<'/Library/Application Support/nowyouhearme/last-session-ztid.txt')
osascript <<EOT
display dialog "NowYouHearMe Connect has detected that you have an unclosed session." & "\n" & "\nClick OK to clear out any open session.\n\nThis will also close TeamViewer and OBS if open." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"OK"}
do shell script "sudo launchctl load '/Library/Application Support/nowyouhearme/zerotier/com.zerotier.one.plist'" with administrator privileges
delay 1
do shell script "sudo /usr/local/bin/zerotier-cli leave $oldztid >>/dev/null 2>&1" with administrator privileges
do shell script "sudo rm -rf '/Library/Application Support/nowyouhearme/last-session-ztid.txt'" with administrator privileges
tell application "TeamViewer" to quit
tell application "OBS" to quit
tell application "Terminal" to quit
EOT
osascript <<EOT
set startnew to display dialog "Your previous NowYouHear.me session has been cleared." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Start New Session"}
if button returned of startnew is "Exit" then 
display dialog "Click OK to Exit.\n\nAlso the Host may want to change their DAW's audio output to internal speakers or an audio interface (set it back to normal)." buttons {"OK"}
tell application "NowYouHearMeConnect" to quit
end if
if button returned of startnew is "Start New Session" then
delay 0.5
end if
EOT
osascript -e 'tell application "Terminal" to quit'
fi
if [ ! -f '/Library/Application Support/nowyouhearme/connectfirstrun.txt' ]; then
osascript <<EOT
set update to display dialog "********************************************" & "\n" & "\n    Welcome to NowYouHear.me Connect     " & "\n" & "\n*********************************************" & "\n\n" & "This program is still in Beta and will need to frequently check for updates to properly work." & "\n" & "\nClick Next to download the latest version." & "\n" & "\nUpdating should take less than 30 seconds.\n\nIF ASKED ON THE NEXT POPUP, YOU MUST CLICK OK TO ALLOW NOWYOUHEARME TO CONTROL TERMINAL." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Skip (not recommended)" , "Next"}
if button returned of update is "Next" then 
tell application "Terminal"
    activate
    do script "'/Library/Application Support/nowyouhearme/script-update'"
end tell 
tell application "Terminal" to close second window
tell application "NowYouHearMeConnect" to quit
	end if
if button returned of update is "Skip (not recommended)" then 
set myQuery to display dialog "*****************************************" & "\n" & "\n Welcome to NowYouHear.me Connect     " & "\n" & "\n*****************************************" & "\n" & "\nPlease pick an option below to begin." & "
" & "
Host - I am a Music Producer wanting to HOST a session. (Someone else will be listening to sound from my DAW)" & "
" & "
Listener - I am a Music Producer, but want to LISTEN to someone else's DAW (I will be listening to someone else's computer)" & "
" & "
2-Way - (Advanced Users) I am a Musician wanting to stream my instrument to a remote studio. (This requires you to also have local recording software such as Garageband, Logic, Ableton, etc)" with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Host", "Listener", "2-Way"}
	if button returned of myQuery is "Host" then
set opt1 to display dialog "You picked Host Mode." & "\n" & "\nYou will be the Music Producer, HOSTING a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps.\n\nIF ASKED ON THE NEXT POPUP, YOU MUST CLICK OK TO ALLOW NOWYOUHEARME TO CONTROL TERMINAL." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt1 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt1 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-host"
end tell 
tell application "Terminal" to close second window
end if
end if
	if button returned of myQuery is "Listener" then
set opt2 to display dialog "You picked Listener Mode" & "\n" & "\nYou will be the Music Producer, LISTENING to a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps.\n\nIF ASKED ON THE NEXT POPUP, YOU MUST CLICK OK TO ALLOW NOWYOUHEARME TO CONTROL TERMINAL." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt2 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt2 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-listener"
end tell 
tell application "Terminal" to close second window
	end if
	end if
	if button returned of myQuery is "2-Way" then
		display dialog "This feature is coming soon!" & "\n" & "\nIn this scenario, the musician and the remote studio would both be acting as Hosts." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit"}
tell application "NowYouHearMeConnect" to quit 
	end if
end if
EOT
fi
if [ -f '/Library/Application Support/nowyouhearme/connectfirstrun.txt' ]; then
osascript <<EOT
set myQuery to display dialog "*********************************************************" & "\n" & "\n                Welcome to NowYouHear.me Connect     " & "\n" & "\n*********************************************************" & "\n" & "\nPlease pick an option below to begin." & "
" & "
Host - I am a Music Producer wanting to HOST a session. (Someone else will be listening to sound from my DAW)" & "
" & "
Listener - I am a Music Producer, but want to LISTEN to someone else's DAW (I will be listening to someone else's computer)" & "
" & "
2-Way - (Advanced Users) I am a Musician wanting to stream my instrument to a remote studio. (This requires you to also have local recording software such as Garageband, Logic, Ableton, etc)" buttons {"Host", "Listener", "2-Way"}
	if button returned of myQuery is "Host" then
set opt1 to display dialog "You picked Host Mode" & "\n" & "\nYou will be the Music Producer, HOSTING a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps.\n\nIF ASKED ON THE NEXT POPUP, YOU MUST CLICK OK TO ALLOW NOWYOUHEARME TO CONTROL TERMINAL." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt1 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt1 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-host"
end tell 
tell application "Terminal" to close second window
end if
end if
	if button returned of myQuery is "Listener" then
set opt2 to display dialog "You picked Listener Mode" & "\n" & "\nYou will be the Music Producer, LISTENING to a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps.\n\nIF ASKED ON THE NEXT POPUP, YOU MUST CLICK OK TO ALLOW NOWYOUHEARME TO CONTROL TERMINAL." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt2 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt2 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-listener"
end tell 
tell application "Terminal" to close second window
	end if
	end if
	if button returned of myQuery is "2-Way" then
		display dialog "This feature is coming soon!" & "\n" & "\nIn this scenario, the musician and the remote studio would both be acting as Hosts." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit"}
tell application "NowYouHearMeConnect" to quit 
	end if
EOT
fi