#!/bin/bash
osver=$(defaults read loginwindow SystemVersionStampAsString | sed 's/10.//g' )
intosver=$(printf %.0f $(echo "$osver" | bc -l))
if [[ $intosver -lt 11 ]]; then 
osascript -e 'display dialog "You need Mac OS 10.11 El Capitan or Higher for this application to work, please upgrade your Mac OS." buttons {"Exit"}'
sleep 1
osascript -e 'tell application "NowYouHearMeConnect" to quit'
osascript -e 'tell application "Terminal" to quit' &
exit
fi
if ! ping -q -c 2 -W 1 8.8.8.8 >/dev/null; then osascript -e 'display dialog "You are not connected to the Internet, or at least NowYouHearMe Connect could not ping Google. \n\nCheck your connection or reboot your computer." buttons {"OK"}' & osascript -e 'tell application "NowYouHearMeConnect" to quit' & osascript -e 'tell application "Terminal" to quit' & exit; fi
if [ ! -f "/Applications/.nowyouhearme/connectfirstrun.txt" ]; then
osascript <<EOT
set update to display dialog "********************************************" & "\n" & "\n    Welcome to NowYouHear.me Connect     " & "\n" & "\n*********************************************" & "\n\n" & "This program is still in Beta and will need to frequently check for updates to properly work." & "\n" & "\nClick Next to download the latest version." & "\n" & "\nUpdating should take less than 30 seconds." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Skip (not recommended)" , "Next"}
if button returned of update is "Next" then 
tell application "Terminal"
    activate
    do script "/Applications/.nowyouhearme/script-update"
end tell 
tell application "Terminal" to close second window
tell application "NowYouHearMeConnect" to quit
	end if
if button returned of update is "Skip (not recommended)" then 
set myQuery to display dialog "*****************************************" & "\n" & "\n Welcome to NowYouHear.me Connect     " & "\n" & "\n*****************************************" & "\n" & "\nPlease pick an option below to begin." & "
" & "
Host - I am a Music Producer wanting to HOST a session. (Someone else will be listening to sound from my DAW)" & "
" & "
Listener - I am a Music Producer, but want to LISTEN to someone else's DAW (I will be listening to someone else's computer)" & "
" & "
2-Way - (Advanced Users) I am a Musician wanting to stream my instrument to a remote studio. (This requires you to also have local recording software such as Garageband, Logic, Ableton, etc)" with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Host", "Listener", "2-Way"}
	if button returned of myQuery is "Host" then
set opt1 to display dialog "You picked Host Mode." & "\n" & "\nYou will be the Music Producer, HOSTING a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt1 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt1 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-host"
end tell 
tell application "Terminal" to close second window
end if
end if
	if button returned of myQuery is "Listener" then
set opt2 to display dialog "You picked Listener Mode" & "\n" & "\nYou will be the Music Producer, LISTENING to a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt2 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt2 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-listener"
end tell 
tell application "Terminal" to close second window
	end if
	end if
	if button returned of myQuery is "2-Way" then
		display dialog "This feature is coming soon!" & "\n" & "\nIn this scenario, the musician and the remote studio would both be acting as Hosts." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"OK"}
tell application "NowYouHearMeConnect" to quit 
	end if
end if
EOT
fi
if [ -f "/Applications/.nowyouhearme/connectfirstrun.txt" ]; then
osascript <<EOT
set myQuery to display dialog "*********************************************************" & "\n" & "\n                Welcome to NowYouHear.me Connect     " & "\n" & "\n*********************************************************" & "\n" & "\nPlease pick an option below to begin." & "
" & "
Host - I am a Music Producer wanting to HOST a session. (Someone else will be listening to sound from my DAW)" & "
" & "
Listener - I am a Music Producer, but want to LISTEN to someone else's DAW (I will be listening to someone else's computer)" & "
" & "
2-Way - (Advanced Users) I am a Musician wanting to stream my instrument to a remote studio. (This requires you to also have local recording software such as Garageband, Logic, Ableton, etc)" buttons {"Host", "Listener", "2-Way"}
	if button returned of myQuery is "Host" then
set opt1 to display dialog "You picked Host Mode" & "\n" & "\nYou will be the Music Producer, HOSTING a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt1 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt1 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-host"
end tell 
tell application "Terminal" to close second window
end if
end if
	if button returned of myQuery is "Listener" then
set opt2 to display dialog "You picked Listener Mode" & "\n" & "\nYou will be the Music Producer, LISTENING to a session." & "\n" & "\nYou will be guided through how to setup your computer for this session in the next few steps." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit" , "Continue"}
if button returned of opt2 is "Exit" then
tell application "NowYouHearMeConnect" to quit 
	end if
if button returned of opt2 is "Continue" then
tell application "Terminal"
    activate
    do script "/Applications/NowYouHearMeConnect.app/Contents/Resources/script-listener"
end tell 
tell application "Terminal" to close second window
	end if
	end if
	if button returned of myQuery is "2-Way" then
		display dialog "This feature is coming soon!" & "\n" & "\nIn this scenario, the musician and the remote studio would both be acting as Hosts." with icon file ("/Applications/NowYouHearMeConnect.app/Contents/Resources/AppIcon.icns" as POSIX file) buttons {"Exit"}
tell application "NowYouHearMeConnect" to quit 
	end if
EOT
fi